version: "3.5"

services:
  web:
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=devproxy_default"
      - "traefik.http.services.devproxy-example-web.loadbalancer.server.port=80"

networks:
  proxy:
    external:
      name: devproxy_default
