version: "3"

services:
  proxy:
    image: traefik:2.0.2
    ports:
      - "80:80"
      - "9080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
